<a href="https://colab.research.google.com/github/Winter-Shade/tutorial-Pytorch/blob/main/2_Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import numpy as np

In [16]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#reshape and view
my_torch = my_torch.reshape(1, 5, 2)
my_torch

tensor([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]])

In [23]:
my_torch.shape

torch.Size([1, 5, 2])

In [27]:
#reshape if we don't know the number of items using -1
my_torch2 = torch.arange(18)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [31]:
my_torch2 = my_torch2.reshape(3, 2, -1)
my_torch2

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])