<a href="https://colab.research.google.com/github/Winter-Shade/tutorial-Pytorch/blob/main/IntroToPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import numpy as np

In [5]:
# TENSORS
# - A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
# - Similar to Numpy Arrays ; Work better on GPU's vs Regular CPU's
# - default data type of float32
# - More suitable for deep learning than a numpy array

## Numpy Arrays

In [7]:
np1 = np.random.rand(3, 4)
np1

array([[0.22243306, 0.71595107, 0.96318656, 0.98355359],
       [0.21802719, 0.0229081 , 0.06362417, 0.57216825],
       [0.06249315, 0.42453237, 0.16668484, 0.00436753]])

In [8]:
np1.dtype

dtype('float64')

## Tensors

In [9]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 0.3607,  0.3494, -0.0851,  0.2081],
        [ 0.1727,  0.9549,  0.9559,  0.0256],
        [-1.9437, -0.1878, -0.4781, -0.3972]])

In [10]:
tensor_2d.dtype

torch.float32

In [15]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2224, 0.7160, 0.9632, 0.9836],
        [0.2180, 0.0229, 0.0636, 0.5722],
        [0.0625, 0.4245, 0.1667, 0.0044]], dtype=torch.float64)