<a href="https://colab.research.google.com/github/Winter-Shade/tutorial-Pytorch/blob/main/L4_pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd

In [2]:
#1 build the neural network using nn module
#2 using built in activation functions
#3 using built in loss function
#4 using built in optimizer

In [4]:
import torch.nn as nn

In [5]:
class Model(nn.Module): #inherit from nn.Module class

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)

    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out



In [10]:
#dataset and model
features = torch.rand([10, 5])
model = Model(features.shape[1])


In [11]:
#call model for forward pass
model(features)

tensor([[0.4310],
        [0.3318],
        [0.3897],
        [0.3747],
        [0.3520],
        [0.2668],
        [0.3349],
        [0.2803],
        [0.3447],
        [0.3597]], grad_fn=<SigmoidBackward0>)

In [13]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.0165, -0.0108, -0.3693, -0.4222,  0.3018]], requires_grad=True)

In [14]:
model.linear.bias

Parameter containing:
tensor([-0.4059], requires_grad=True)

In [15]:
! pip install torchinfo

In [16]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [18]:
## Example - 2
## Neural network with 5 inputs (x_i's), 2 layers: (3 outputs from 1st hidden layer ; 1 output from outer layer)

In [20]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.linear2 = nn.Linear(3, 1)
    self.relu = nn.ReLU()
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out1 = self.linear1(features)
    out1 = self.relu(out1)

    out2 = self.linear2(out1)
    out2 = self.sigmoid(out2)

    return out2


In [22]:
#dataset and model
features = torch.rand([10, 5])

model = Model(features.shape[1])

#call model for forward pass : model(features)
model(features)

tensor([[0.5011],
        [0.5058],
        [0.4987],
        [0.5216],
        [0.5102],
        [0.4976],
        [0.5084],
        [0.5037],
        [0.4994],
        [0.5151]], grad_fn=<SigmoidBackward0>)

In [26]:
model.linear1.weight

Parameter containing:
tensor([[ 0.2841, -0.2172,  0.0674, -0.0628,  0.1500],
        [-0.2957,  0.3109, -0.3588,  0.2160,  0.3495],
        [ 0.1050, -0.0981, -0.1624,  0.3889,  0.1013]], requires_grad=True)

In [27]:
model.linear1.bias

Parameter containing:
tensor([-0.2974, -0.4250,  0.3413], requires_grad=True)