<a href="https://colab.research.google.com/github/Winter-Shade/tutorial-Pytorch/blob/main/PyTorch_L1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'2.5.1+cu124'

In [3]:
if torch.cuda.is_available():
  print("GPU Available")
  print(f'Device Name: {torch.cuda.get_device_name(0)}')
else:
  print("GPU not available, using CPU")

GPU Available
Device Name: Tesla T4


## Tensors


In [9]:
# empty - allocates memory
a = torch.empty(3, 2)
a, type(a)

(tensor([[9.6849e-34, 0.0000e+00],
         [0.0000e+00, 2.3510e-38],
         [3.9818e-37, 0.0000e+00]]),
 torch.Tensor)

In [10]:
#zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
#ones
torch.ones(1,6, dtype=torch.int32)

tensor([[1, 1, 1, 1, 1, 1]], dtype=torch.int32)

In [21]:
# rand and manual_seed
torch.manual_seed(120)
torch.rand(2,3, dtype=torch.float16)

tensor([[0.8315, 0.8750, 0.5771],
        [0.3589, 0.6865, 0.0049]], dtype=torch.float16)

In [26]:
# tensor
torch.tensor([[1, 1, 2, 5], [2, 3, 4, 9]])

tensor([[1, 1, 2, 5],
        [2, 3, 4, 9]])

In [28]:
#other options - linspace, arange, eye, full
torch.eye(3) #identity matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [29]:
torch.full((2,3), 100)

tensor([[100, 100, 100],
        [100, 100, 100]])

## Tensor Shapes


In [38]:
x = torch.tensor([[1], [4]])
x.shape

torch.Size([2, 1])

In [40]:
a = torch.empty_like(x)
a

tensor([[283047579811840],
        [            372]])

In [41]:
b = torch.ones_like(x, dtype=torch.float64)
b

tensor([[1.],
        [1.]], dtype=torch.float64)

In [50]:
y = torch.rand_like(x, dtype=torch.float32)
y

tensor([[0.8265],
        [0.6202]])

## Tensor Data Types

In [43]:
x.dtype

torch.int64

In [45]:
torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [47]:
#using to
x.to(torch.float32)

tensor([[1.],
        [4.]])

## Mathematical Operations

### 1. Scalar Operations

In [51]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
x

In [60]:
#addition
x + 2
#substraction
x - 1
#mutliplication
2 * x
#division (float32)
x / 3
#int division
(x*5)//3
#mod
((x*5)//3)%2
#scalar
x**2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

### 2. Element Wise Operations

In [14]:
a = torch.rand(2,3)
b = torch.ones(2,3)
b[0][0] = 2
print(a)
print(b)

tensor([[0.3067, 0.5635, 0.2745],
        [0.8311, 0.9233, 0.8133]])
tensor([[2., 1., 1.],
        [1., 1., 1.]])


In [15]:
#add
a + b
#subtraction
a - b
# multiply
a * b
# division
a / b
#int division
a // b
#power
a ** b

tensor([[0.0940, 0.5635, 0.2745],
        [0.8311, 0.9233, 0.8133]])

In [18]:
# other operations - abs, neg, ceil, round, floor, clamp
torch.clamp(a, min=0.1, max=0.4)

tensor([[0.3067, 0.4000, 0.2745],
        [0.4000, 0.4000, 0.4000]])

### 3. Reduction Operation

In [37]:
e = torch.randint(size=(2,4), low=1, high=9, dtype=torch.float32)
e[1][0] = 0
e

tensor([[1., 6., 5., 3.],
        [0., 8., 4., 4.]])

In [28]:
#sum of all elements
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
#sum along rows
torch.sum(e, dim=1)

tensor([24., 18.])

In [31]:
#mean
torch.mean(e)
#mean along columns
torch.mean(e, dim=0)
# mean along rows
torch.mean(e, dim=1)

tensor([6.0000, 4.5000])

In [34]:
# other operations - max, min, median, prod : product of all items
torch.prod(e)
torch.median(e)
torch.max(e)

tensor(8.)

In [35]:
# standard deviation, variance
torch.std(e), torch.var(e)

(tensor(2.6049), tensor(6.7857))

In [38]:
torch.argmax(e)

tensor(5)

In [39]:
torch.argmin(e)

tensor(4)

### 4. Matrix Operations

In [40]:
f = torch.randint(size=(2,3), low=1, high=10)
g = torch.randint(size=(3,2), low=1, high=9)

print(f)
print(g)

tensor([[3, 7, 1],
        [3, 7, 8]])
tensor([[2, 6],
        [3, 1],
        [7, 1]])


In [41]:
#matrix multiplication
torch.matmul(f,g)

tensor([[34, 26],
        [83, 33]])

In [45]:
vector1 = torch.tensor([2, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(14)

In [46]:
#transpose
torch.transpose(f, 0, 1)

tensor([[3, 3],
        [7, 7],
        [1, 8]])

In [47]:
#other operations: determinant: det(), inverse: inverse()

### 6.Special Functions

In [49]:
h = torch.randint(size=(2,3), low=1, high=10, dtype=torch.float32)
h

tensor([[4., 2., 7.],
        [1., 9., 4.]])

In [50]:
#log
torch.log(h)

tensor([[1.3863, 0.6931, 1.9459],
        [0.0000, 2.1972, 1.3863]])

In [51]:
#exp
torch.exp(h)

tensor([[5.4598e+01, 7.3891e+00, 1.0966e+03],
        [2.7183e+00, 8.1031e+03, 5.4598e+01]])

In [53]:
#sqrt
torch.sqrt(h)

tensor([[2.0000, 1.4142, 2.6458],
        [1.0000, 3.0000, 2.0000]])

In [54]:
#sigmoid
torch.sigmoid(h)

tensor([[0.9820, 0.8808, 0.9991],
        [0.7311, 0.9999, 0.9820]])

In [56]:
#softmax
torch.softmax(h, dim=0)

tensor([[9.5257e-01, 9.1105e-04, 9.5257e-01],
        [4.7426e-02, 9.9909e-01, 4.7426e-02]])

In [57]:
#relu
torch.relu(h)

tensor([[4., 2., 7.],
        [1., 9., 4.]])

## Inplace Operations

In [61]:
m = torch.randint(size=(2,3), low=1, high=10, dtype=torch.float32)
n = torch.randint(size=(2,3), low=1, high=10, dtype=torch.float32)

print(m)
print(n)

tensor([[3., 4., 4.],
        [6., 3., 5.]])
tensor([[1., 5., 6.],
        [4., 5., 7.]])


In [62]:
m.add_(n)
m

tensor([[ 4.,  9., 10.],
        [10.,  8., 12.]])

In [63]:
torch.relu(m)

tensor([[ 4.,  9., 10.],
        [10.,  8., 12.]])

In [65]:
m[0][0] = -1
m.relu_()

tensor([[ 0.,  9., 10.],
        [10.,  8., 12.]])

## Copying a tensor
- tensor is a reference type

In [67]:
m = torch.rand(2, 3)
m

tensor([[0.3085, 0.5938, 0.2521],
        [0.8854, 0.3696, 0.6408]])

In [69]:
a = m

In [71]:
id(a), id(m) #same location

(133186665997488, 133186665997488)

In [72]:
b = a.clone()

In [73]:
id(a), id(b)

(133186665997488, 133186650906672)

# Tensor Operations on GPU

In [75]:
torch.cuda.is_available()

True

In [76]:
device = torch.device('cuda')

In [78]:
#creating a new tensor on GPU
torch.rand(size=(2,3), device = device)

tensor([[0.5541, 0.3540, 0.3769],
        [0.1852, 0.4650, 0.8695]], device='cuda:0')

In [79]:
# moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.2680, 0.6558, 0.5370],
        [0.6661, 0.3634, 0.5999]])

In [82]:
b= a.to(device)
b + 6

tensor([[6.2680, 6.6558, 6.5370],
        [6.6661, 6.3634, 6.5999]], device='cuda:0')

In [87]:
import time
matrix1 = torch.randint(size=(10000,10000), low=1, high=5, dtype=torch.float32)
matrix2 = torch.randint(size=(10000,10000), low=1, high=5, dtype=torch.float32)

start_time = time.time()
operation = torch.matmul(matrix1, matrix2)
end_time = time.time()
cpu_time = end_time - start_time
print(f'CPU Time: {end_time - start_time}')

# move the matrices to cuda
mat1 = matrix1.to('cuda')
mat2 = matrix2.to('cuda')

start_time = time.time()
operation = torch.matmul(mat1, mat2)
torch.cuda.synchronize() #Ensure all GPU operations are complete
end_time = time.time()
gpu_time = end_time - start_time
print(f'GPU Time: {end_time - start_time}')
print(f'\n\nSpeedup : {cpu_time/ gpu_time}')

CPU Time: 24.38279891014099
GPU Time: 0.47296762466430664


Speedup : 51.55278636132213


## Reshaping Tensors

In [89]:
a = torch.rand(size=(3,4))
a

tensor([[0.5614, 0.0360, 0.1105, 0.8054],
        [0.8556, 0.1509, 0.2136, 0.3718],
        [0.0014, 0.4202, 0.3991, 0.2220]])

## Reshape

In [2]:
a = torch.randint(size=(4,4), low=1, high=10, dtype=torch.float32)
a

tensor([[9., 5., 5., 6.],
        [7., 6., 6., 7.],
        [5., 6., 3., 2.],
        [9., 6., 2., 2.]])

In [3]:
a.to('cuda')
a

tensor([[9., 5., 5., 6.],
        [7., 6., 6., 7.],
        [5., 6., 3., 2.],
        [9., 6., 2., 2.]])

In [4]:
a.reshape(2,2,2,2)

tensor([[[[9., 5.],
          [5., 6.]],

         [[7., 6.],
          [6., 7.]]],


        [[[5., 6.],
          [3., 2.]],

         [[9., 6.],
          [2., 2.]]]])

In [5]:
a.flatten()

tensor([9., 5., 5., 6., 7., 6., 6., 7., 5., 6., 3., 2., 9., 6., 2., 2.])

In [8]:
#permute
a = torch.rand(size=(2,3,4), device='cuda')

tensor([[[0.8344, 0.1561, 0.7609, 0.1783],
         [0.7894, 0.2516, 0.1488, 0.0014],
         [0.1754, 0.2686, 0.6986, 0.6644]],

        [[0.6507, 0.0479, 0.2309, 0.4813],
         [0.3113, 0.0030, 0.8182, 0.5626],
         [0.2192, 0.5422, 0.7838, 0.1723]]], device='cuda:0')

In [9]:
#permute
a.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [10]:
#unsqueeze
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [11]:
#squeeze
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])